name: Flask CI/CD
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Flask app
        run: python app/main.py &
      - name: Run unit tests
        run: python -m pytest tests/  #
      - name: Run BDD tests
        run: behave features/